spring:
  mvc:
    default-content-type: application/json
  shutdown: graceful
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 20s
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:file:/data/demoDB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      generate-ddl: true
      properties:
        hibernate:
          jdbc.batch_size: 100
          order_inserts: true
          order_updates: true
          jdbc:
            batch_versioned_data: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,metrics,httptrace,prometheus
      base-path: /app/


springdoc:
  swagger-ui:
    disable-swagger-default-url: true

mock:
  service:
    url: "dev.service"

