spring:
  mvc:
    default-content-type: application/json
  shutdown: graceful
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 20s
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  #    h2:
  #      console.enabled: true
  #      console:
  #        path: /h2-console
  #        settings.trace: false
  #        settings.web-allow-others: false
  #        ed
  datasource:
    url: jdbc:postgresql://localhost:54329/loan_provisioning_system
    username: postgres
    password: admin
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        #          generate_statistics: true
        #          session:
        #            event:
        #              log:
        #                LOG_QUERIES_SLOWER_THAN_MS: 3
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        ddl-auto: update
        jdbc:
          batch_versioned_data: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,metrics,httptrace,prometheus
      base-path: /app/


springdoc:
  swagger-ui:
    disable-swagger-default-url: true

#MOCK URL AND API KEY
mock:
  service:
    url: "https://credit-bureau-dev.service"
    apiKey: "q9F/DEsYSR+7NQMs5IXRbOep1z92EPZlLfEBtVsf6VCa5pBTY9SU1/Lzi+kgK6qZBTtF8NjWBfK9yUFkgHORRg=="
  bank:
    url: "https://sample-bank-api.dev.com"
    apiKey: "xzqs9ERIzROgbLNS031vjBpoKhXphthlFmuqadOtaImUi3veSiJ+K9o1+DvO50SMw+4OQvG9Eg7DYVOv7o2mUQ=="

# LOAN SPECIFIC CONFIG
main-account: 10000454003453450345
interest-rate: 0.12 # 12% annual interest rate
origination-fee-rate: 0.01

#MAILER CONFIG FOR SMTP
mailer-config:
  baseUrl: ""
  apiToken: ""
  protocol: smtp
  host: ""
  port: 587
  username: ""
  password: ""
  smtpAuth: true
  smtpStarttlsEnable: true
  sslEnable: false

#EMAIL TEMPLATE WE CAN USE SENDING DIFFERENT MESSAGE
email-config:
  from: ""
  verifyEmailSubject: "Confirm your identity for your account"
  verifyEmailContent: "Dear {0}, Thank you for creating an account on {1} portal. Please use the OTP code below and sign into your account to verify your email address and complete your registration. Your one time verification code(OTP) is {2}"
  accountVerifiedSubject: "Your account has been verified"
  accountVerifiedContent: "Congratulations!! You have successfully completed your registration."
  passwordForgotSubject: "Forgot password confirmation"
  passwordForgotContent: "Dear {0}, Forgot password process has been initiated,  Please use the OTP code below to change your password. Your one time verification code(OTP) is {1}"
  resetSuccessSubject: "Password reset successful"
  resetSuccessContent: "Dear {0}, Your password has been changed."
  emailChangeSubject: "Email change request verification"
  emailChangeInitiate: "Dear {0}, Your change email request OTP is {1}, please use this to finalise your process."
  phoneChangeSubject: "Phone change request verification"
  phoneChangeInitiate: "Dear {0}, Your change phone request OTP is {1}, please use this to finalise your process."
  appName: "Loan provisioning system"

#MOCK API KEY FOR EXTERNAL SERVICE INTEGRATION
apikey: dc79b0dfd0f5807e78cf8a445cd22a70
secretkey: 01c89b290ac5fa9a8284d196b90df337


# BELOW RULES NOT USED AS WE ARE USING DROOLS RULE ENGIN
loan:
  validationRules:
    rule-1:
      minCreditScore: 700
      maxDTIRatio: 0.4
      additionalValidationsRequired: true
      approvalStrategy: AUTOMATIC
    rule-2:
      minCreditScore: 600
      maxDTIRatio: 0.5
      additionalValidationsRequired: true
      approvalStrategy: MANUAL
    rule-3:
      minCreditScore: 0
      maxDTIRatio: 1.0
      additionalValidationsRequired: false
      approvalStrategy: REJECTED
  alternativeCreditDataRules:
    changeOfAddressThreshold: 3
    changeOfAddressPeriod: 3
    lateRentalPaymentsThreshold: 4
    lateRentalPaymentsPeriod: 24
    lateCellPhonePaymentsThreshold: 1
    lateCellPhonePaymentsPeriod: 12
  autoStructuringRules:
    downPaymentIncrement: 500
    monthlyPaymentReductionPercent: 5
    dtiCap: 15
    loanTermIncrementMonths: 3
    maxLoanTermMonths: 84
    monthlyPaymentReductionAmount: 50
    interestRateIncreasePercent: 0.25
  processingPipeline:
    - initialCreditScoreAndDTICheck
    - alternativeCreditDataAssessment
    - autoStructuringProcess
    - finalDecision